from board import Board

b1 = Board()
print(b1.who_won())
b1.make_move(0, 0, 'X')
b1.make_move(1, 0, 'O')
b1.make_move(2, 0, 'X')
b1.make_move(1, 1, 'O')
b1.make_move(1, 2, 'X')
b1.make_move(0, 1, 'O')
b1.make_move(2, 1, 'X')
b1.make_move(2, 2, 'O')
b1.make_move(0, 2, 'X')
b1.undo_move(0, 2)
b1.undo_move(2, 2)
b1.undo_move(2, 1)
b1.undo_move(0, 1)
b1.print_out()
print(b1.game_over())
print(b1.who_won())
print(b1.actions())

b2 = Board()
b2.make_move(0, 0, 'X')
b2.make_move(1, 0, 'X')
b2.make_move(2, 0, 'X')
b2.print_out()
print(b2.who_won())
print(b2.actions())

b3 = Board()
b3.make_move(0, 0, 'O')
b3.make_move(0, 1, 'O')
b3.make_move(0, 2, 'O')
b3.print_out()
print(b3.who_won())
print(b3.actions())

b4 = Board()
b4.play_game()